on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --all -- --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install 1.72 --profile minimal
      - uses: Swatinem/rust-cache@v2
      - run: cargo test
